apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-firefox
  labels:
    app.kubernetes.io/part-of: Nodes
    app.kubernetes.io/component: backend
  annotations:
    app.openshift.io/connects-to: hub
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: selenium
      deployment: selenium-node-firefox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: selenium
        deployment: selenium-node-firefox
    spec:
      containers:
      - env:
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"
        - name: SE_EVENT_BUS_HOST
          value: selenium
        - name: SE_OFFLINE
          value: "true"
        - name: SE_JAVA_OPTS
          value: -Xmx512m
        image: selenium/node-firefox:116.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 5555
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: selenium-node-firefox
        ports:
        - containerPort: 5555
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 5555
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: selenium
      serviceAccountName: selenium
      terminationGracePeriodSeconds: 30
      volumes:
      - name: shm
        emptyDir:
          medium: "Memory"