apiVersion: v1
kind: Service
metadata:
  name: selenium
  labels:
    app: selenium
spec:
  ports:
  - name: 4444-http
    port: 4444
    protocol: TCP
    targetPort: 4444
  - name: 4443-tcp
    port: 4443
    protocol: TCP
    targetPort: 4443
  - name: 4442-tcp
    port: 4442
    protocol: TCP
    targetPort: 4442
  selector:
    app: selenium
    deployment: selenium-hub
  sessionAffinity: None
  type: ClusterIP
